### ISSUE TITLE
Generated signature does not match submitted signature.

### ISSUE THREAD

**Issue by tjhunkin** [PayFast/payfast-php-sdk#1]
If anyone is struggling with this error: **Generated signature does not match submitted signature.**

You need to make sure your passPhrase is set.

Also that your payload data is in the correct order.

Mine is as follows:

- 'return_url'   
- 'cancel_url'   
- 'notify_url'   
- 'name_first'   
- 'name_last'    
- 'email_address'
- 'cell_number'  
- 'm_payment_id' 
- 'amount'       
- 'item_name'

**Comment by clairepf** [comment]
Thanks for the above.

Just to note there are 2 signatures, if you are using Custom or Onsite integrations then the above is correct.
https://developers.payfast.co.za/docs#step_2_signature

If you are using the API, please note the payload order is alphabetical (the SDK does handle the sorting on this)
https://developers.payfast.co.za/api#authentication

**Comment by tjhunkin** [comment]
I'm getting this error again using a **basic payment form**. _"Generated signature does not match submitted signature"_

I'm in production mode.

I'm using R5 to make sure it's not the limit issue.

But if I delete the hidden signature field from the form before submitting it, the offsite link works fine. (Enable Require Signature as Disabled)

If I enable the "Enable Require Signature" setting and leave the hidden signature field in the form, it still doesn't work. Same error.

If I leave out the hidden signature field, it says "Signature is required". Which means if the setting is enabled, that it does indeed look for that.

The signature generated by the SDK seems to be incorrect then.

I also took your custom sample app and put my merchant key and merchant id in and set test to false and it gives the same error.

Any ideas?

**Comment by tjhunkin** [comment]
I found and logged the issue here: https://github.com/PayFast/payfast-php-sdk/issues/4
