### ISSUE TITLE
SAME ERROR ALL DETAILS CORRECT!

### ISSUE THREAD

**Issue by lynxionxs** [PayFast/payfast-php-sdk#10]
In the LIVE SITE it keeps showing ```signature: Generated signature does not match submitted signature.``` . It's working fine in the SANDBOX. Even with the demo ```examples/custom/``` it shows the same error on the LIVE SITE. All details are correct
What's going on?

```php
<?php

// v1.1.3

require('vendor/autoload.php');

use PayFast\PayFastPayment;

$amount = '12.00';
$url = '';
$isDev = false;
$settings = [];

// LIVE SETTINGS
if ($isDev) {

	// SANDBOX SETTINGS
	$url = 'https://b5c9-105-9-212-52.eu.ngrok.io';

	$settings = [
		'merchantId' => '12345678',
		'merchantKey' => 'wertryjrthrthrtt',
		'passPhrase' => 'The-SANDBOX-Phrase-123',
		'testMode' => $isDev
	];

} else {

	// LIVE SITE SETTINGS
	$url = 'https://example.com';

	$settings = [
		'merchantId' => '87654321',
		'merchantKey' => 'dft5uy75y435g',
		'passPhrase' => 'The-LIVE-SITE-Phrase-123',
		'testMode' => $isDev
	];

}

$payfast = new PayFastPayment($settings);

// get date when paid subscription starts
$currDate = new DateTime();
$currDate->modify("+7 days");
$recurringDate = $currDate->format("Y-m-d");

$data = [
	// Merchant details
	'return_url' => $url.'/pf-custom/return.php',
	'cancel_url' => $url.'/pf-custom/cancel.php',
	'notify_url' => $url.'/pf-custom/notify.php',
	// Buyer details
	'name_first' => 'First Name',
	'name_last'  => 'Last Name',
	'email_address' => 'test@test.com',
	// Transaction details
	'm_payment_id' => '1234',
	'amount' => '0.00',
	'item_name' => 'Order#123',
	// Subscription fields
	'subscription_type' => '1',
	'billing_date' => $recurringDate,
	'recurring_amount' => $amount,
	'frequency' => '3',
	'cycles' => '0',
	'subscription_notify_email' => 'true',
	'subscription_notify_webhook' => 'true',
	'subscription_notify_buyer' => 'true'
];

$htmlForm = $payfast->custom->createFormFields($data, ['value' => 'PLEASE PAY', 'class' => 'button-cta']);
?>

<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>Checkout</title>
	<link rel="stylesheet" href="css/main.css">
</head>

<body>

	<div class='subject'>Checkout&nbsp;&nbsp;Check<br>Checkout&nbsp;&nbsp;Check</div>

	<div class='checkout'>
		<div class='order'>
			<h2>Custom Checkout Demo</h2>
			<h5>Order #000001</h5>
			<ul class='order-list'>
				<li><img src='https://via.placeholder.com/150'>
					<h4>Product 1</h4>
					<h5>R2</h5>
				</li>
				<li><img src='https://via.placeholder.com/150'>
					<h4>Product 2</h4>
					<h5>R1</h5>
				</li>
				<li><img src='https://via.placeholder.com/150'>
					<h4>Product 3</h4>
					<h5>R1</h5>
				</li>
			</ul>
			<h5>Shipping</h5>
			<h4>R 1.00</h4>
			<h5 class='total'>Total</h5>
			<h1>R <?= $amount; ?></h1>

			<?= $htmlForm; ?>

		</div>
	</div>

</body>

</html>

```

**Comment by lefu007** [comment]
Good Day,

Thank you for reporting this, I am attending to a fix.

I'll get back to you this afternoon.

Kind regards

**Comment by lefu007** [comment]
Good Day,

We have pushed a fix for signature.

Kind regards

**Comment by lynxionxs** [comment]
Hi @lefu007 . The fix doesn't show the signature error anymore, but a new error on the Live Site, 
```You are unable to proceed with this transaction, please contact our support team at support@payfast.co.za for further assistance.```
![Screenshot_2023-01-02_08-44-19](https://user-images.githubusercontent.com/7606938/210201570-fd636c65-8baf-45cc-a25a-06a97942694d.png)

**Comment by Baggins800** [comment]
The `generateSignature()` missed a few internal fields,
```
'subscription_notify_email',
'subscription_notify_webhook',
'subscription_notify_buyer'
```
which was added in 897e88dabc99283e891d6f8dbad25ccca7a787b9, but the fields where then ordered according to `$data`, which will generate the wrong signature. A fix for you now will likely be ordering the $data according to
```
'merchant_id', 'merchant_key', 'return_url', 'cancel_url', 'notify_url',
            'name_first', 'name_last', 'email_address', 'cell_number',
            'm_payment_id', 'amount', 'item_name', 'item_description',
            'custom_int1', 'custom_int2', 'custom_int3', 'custom_int4', 'custom_int5',
            'custom_str1', 'custom_str2', 'custom_str3', 'custom_str4', 'custom_str5',
            'email_confirmation', 'confirmation_address',
            'payment_method',
            'subscription_type', 'billing_date', 'recurring_amount', 'frequency', 'cycles'
```
Although, I am unsure when the `'merchant_id', 'merchant_key'` are added.

If that does not work, I opened a pull request (https://github.com/PayFast/payfast-php-sdk/pull/11) if you want to see the solution.

**Comment by lynxionxs** [comment]
> The `generateSignature()` missed a few internal fields,
> 
> ```
> 'subscription_notify_email',
> 'subscription_notify_webhook',
> 'subscription_notify_buyer'
> ```
> 
> which was added in [897e88d](https://github.com/PayFast/payfast-php-sdk/commit/897e88dabc99283e891d6f8dbad25ccca7a787b9), but the fields where then ordered according to `$data`, which will generate the wrong signature. A fix for you now will likely be ordering the $data according to
> 
> ```
> 'merchant_id', 'merchant_key', 'return_url', 'cancel_url', 'notify_url', 'notify_method',
>             'name_first', 'name_last', 'email_address', 'cell_number', 'm_payment_id', 'amount', 'item_name',
>             'item_description', 'custom_int1', 'custom_int2', 'custom_int3', 'custom_int4', 'custom_int5',
>             'custom_str1', 'custom_str2', 'custom_str3', 'custom_str4', 'custom_str5', 'email_confirmation',
>             'confirmation_address', 'currency', 'payment_method', 'subscription_type', 'passphrase',
>             'billing_date', 'recurring_amount', 'frequency', 'cycles', 'subscription_notify_email',
>             'subscription_notify_webhook', 'subscription_notify_buyer'
> ```
> 
> Although, I am unsure when the `'merchant_id', 'merchant_key'` are added.
> 
> If that does not work, I opened a pull request (#11) if you want to see the solution.
> 
> Edit: added `'subscription_notify_email', 'subscription_notify_webhook', 'subscription_notify_buyer'`

Hi. The fields are ordered the same way. Here is the generated form . The merchant_id and merchant_key are added by the SDK to the form, from the $payfast initializing step.
```html 
<form action="https://www.payfast.co.za/eng/process" method="post">
  <input name="merchant_id" type="hidden" value="123456" />
  <input name="merchant_key" type="hidden" value="143rft54y45t35" />
  <input name="return_url" type="hidden" value="https://example.com/pf-custom/return.php" />
  <input name="cancel_url" type="hidden" value="https://example.com/pf-custom/cancel.php" />
  <input name="notify_url" type="hidden" value="https://example.com/pf-custom/notify.php" />
  <input name="name_first" type="hidden" value="First Name" />
  <input name="name_last" type="hidden" value="Last Name" />
  <input name="email_address" type="hidden" value="test@test.com" />
  <input name="m_payment_id" type="hidden" value="1234" />
  <input name="amount" type="hidden" value="0.00" />
  <input name="item_name" type="hidden" value="Order#123" />
  <input name="subscription_type" type="hidden" value="1" />
  <input name="billing_date" type="hidden" value="2023-01-09" />
  <input name="recurring_amount" type="hidden" value="12.00" />
  <input name="frequency" type="hidden" value="3" />
  <input name="cycles" type="hidden" value="0" />
  <input name="subscription_notify_email" type="hidden" value="true" />
  <input name="subscription_notify_webhook" type="hidden" value="true" />
  <input name="subscription_notify_buyer" type="hidden" value="true" />
  <input name="signature" type="hidden" value="d4aa96fa11a3b745609ebef47e40db08" />
  <input type="submit" value="PLEASE PAY" value="PLEASE PAY" class="button-cta" />
</form>
```

**Comment by Baggins800** [comment]
This strange - I get the same, but if I add `confirmation_address` and `email_confirmation` the generated signature corresponds to the sandbox generated signature.  I am not sure about the `subscription_notify_*` fields, they cannot be specified on the sandbox test, the webhook seem to be active by default. I am unsure where we can test the `subscription_notify_*`  fields from the sandbox side, maybe remove them at this stage?

_A semi related side-note, if you intend to use `custom_str*`, make sure you and `rtrim(base64_encode($value), '=')` , since the values can only be alphanumeric, the `generateSignature(...)` function does not care if you use something other than alphanumeric characters, but the sandbox "Test your integration" does._

**Comment by lynxionxs** [comment]
I removed ``` subscription_notify_* ``` fields, and in the Sandbox worked as expected. But the Live Site not. Same error 
``` You are unable to proceed with this transaction, please contact our support team at support@payfast.co.za for further assistance. ```. Adding ```confirmation_address``` and ```email_confirmation``` gives Signature mismatch error.

**Comment by Baggins800** [comment]
I am not sure if this helps, but check if the `email_address` is not the same email as the registered email on payfast.co.za, see [error](https://support.payfast.co.za/portal/en/kb/articles/why-am-i-getting-a-merchant-is-unable-to-receive-payments-from-the-same-account-error).

**Comment by lynxionxs** [comment]
> I am not sure if this helps, but check if the `email_address` is not the same email as the registered email on payfast.co.za, see [error](https://support.payfast.co.za/portal/en/kb/articles/why-am-i-getting-a-merchant-is-unable-to-receive-payments-from-the-same-account-error).

I am not using the same email address as the payfast account.

**Comment by lynxionxs** [comment]
I got it working. Thanks.
