### ISSUE TITLE
Error with the signature when I add a return_url or any url parameter to the PayfastPayment class using a custom integration

### ISSUE THREAD

**Issue by valkyriweb** [Payfast/payfast-php-sdk#13]
Hey team, thanks for making this package. 

I am having a weird issue where if I add a return_url, cancel_url or notify_url to the $payfast->custom->createFormFields() method I get a response on the sandbox website that says the generated signature does not match.

If I remove the URL parameters everything works as intended but I am not redirected after cancelling or making a test payment..

If I add a URL without "https://" it will allow me to go to another page that says the URL is invalid, so I'm not sure if there is an issue with the URL's in the parameters.

Maybe I am doing something wrong, but I have had a look at the PayFastPayment Class and I don't see anything out of the ordinary.

<img width="1130" alt="Screenshot 2023-04-06 at 14 48 27" src="https://user-images.githubusercontent.com/26508155/230383207-36b08b8d-124c-438c-9a77-65bb8ba71690.png">

<img width="1287" alt="Screenshot 2023-04-06 at 14 49 01" src="https://user-images.githubusercontent.com/26508155/230383313-98133250-028b-471b-99dc-3889d058db8a.png">

**Comment by Sheldon-Knight** [comment]
i have the same issue

**Comment by valkyriweb** [comment]
@Sheldon-Knight Hey man, ye I managed to fix it by forking the PHP SDK and merging in one of the PR's, it's a weird issue with the order of items in the array used to generate the signature.

Check - https://github.com/bermont-digital/payfast-php-sdk

I created a package as well to use for my own projects, the problem is I probably won't be maintaining it - 

https://packagist.org/packages/bermont-digital/payfast-php-sdk-fork

**Comment by Sheldon-Knight** [comment]
ty m man i appreciate it

**Comment by valkyriweb** [comment]
No worries man, hope you came right
