### ISSUE TITLE
BC in v1.1.5

### ISSUE THREAD

**Issue by chrisnoden** [Payfast/payfast-php-sdk#15]
The changes to the composer.json mean this new tagged release is a breaking change. Anybody who already had v1.1.4 or older working will not be able to easily update to v1.1.5

Users who update will no longer be able to use the library - composer will report an error with the PSR4 validity of the package.

You should revert all namespace changes and the composer.json autoload->psr4 modification to ensure updating to v1.1.5 is not a breaking change.

**Comment by DarronEngelbrecht** [comment]
Hmmm... I don't think this issue will show up on Mac and Windows due to case insensitive filesystems?

**Comment by appinlet** [comment]
@chrisnoden @DarronEngelbrecht thank you for raising this. v1.1.5 is a breaking change which we've noted in the readme file.

**Comment by bruce-atkinson** [comment]
@chrisnoden @DarronEngelbrecht this is now resolved in v1.1.6.
