### ISSUE TITLE
Composer says this package is abandoned

### ISSUE THREAD

**Issue by lynxionxs** [Payfast/payfast-php-sdk#16]
What does this message mean when installing this package ? 
 ```Package payfast/payfast-php-sdk is abandoned, you should avoid using it. No replacement was suggested.```
Is this no longer going to work or be worked on ? Should we now be using the php spaghetti code that's in the docs ?

**Comment by tjhunkin-inhance** [comment]
Hmmm...same question, just saw it now

**Comment by bruce-atkinson** [comment]
@lynxionxs @tjhunkin-inhance, this issue is being investigated. The package is still supported.

**Comment by rdvr** [comment]
I think it is just a status flag that needs to be corrected on Packagist

![Screenshot from 2024-03-11 10-22-00](https://github.com/Payfast/payfast-php-sdk/assets/20470763/9ced5efa-24bc-4b5e-806a-d1b80358fdb5)

**Comment by gmurambadoro** [comment]
The package is still saying "abandoned".

**Comment by bruce-atkinson** [comment]
The abandoned flag has been removed.
