### ISSUE TITLE
Onsite Payments Notification: cell_number not returned

### ISSUE THREAD

**Issue by tjhunkin** [PayFast/payfast-php-sdk#3]
After making an Onsite Payment, the Customer's cell_number is not in the POSTed notify_url

**Comment by clairepf** [comment]
Thank you, will let you know when there is a resolution.

**Comment by clairepf** [comment]
@tjhunkin The cell_number is currently not available in any of the notification webhook payloads, there will be communication when it becomes available in a future version.
