### ISSUE TITLE
BUG: CustomIntegration not using Pass Phrase when generating Signature

### ISSUE THREAD

**Issue by tjhunkin** [PayFast/payfast-php-sdk#4]
Good Day

On line 34 of payfast-php-sdk\lib\PaymentIntegrations\CustomIntegration.php

The signature is generated as:

`$signature = Auth::generateSignature($data);`

But it needs to be:

`$signature = Auth::generateSignature($data,PayFastPayment::$passPhrase ?? null);`

Otherwise the error: "Generated signature does not match submitted signature." occurs

**Comment by clairepf** [comment]
Thank you, updated in v1.0.1

**Comment by tjhunkin** [comment]
No, Thank You!
